DROP TABLE IF EXISTS users, items, bookings, item_request, comments;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512) UNIQUE                     NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS item_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  VARCHAR(4000)               NOT NULL,
    requester_id BIGINT REFERENCES users (id),
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR(4000),
    available   BOOLEAN,
    owner_id    BIGINT REFERENCES users (id),
    request_id  BIGINT REFERENCES item_requests (id),
    CONSTRAINT UQ_OWNER_ITEM_NAME UNIQUE (owner_id, name)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date_time   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id         BIGINT REFERENCES items (id),
    booker_id       BIGINT REFERENCES users (id),
    status          VARCHAR(50)                 NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      VARCHAR(4000)               NOT NULL,
    item_id   BIGINT REFERENCES items (id),
    author_id BIGINT REFERENCES users (id),
    created   TIMESTAMP WITHOUT TIME ZONE NOT NULL
);